name: Windows Exe Olustur

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Kutuphaneleri Yukle
      # Olası gizli bağımlılık sorunlarını önlemek için scipy'yi de ekledim
      run: pip install pandas openpyxl pyinstaller scikit-learn xgboost numpy scipy

    - name: EXE Olustur
      # Önceki hatayı çözen --collect-data ve --copy-metadata satırları eklendi
      run: |
        pyinstaller --noconsole --onedir --name SatisSimulasyonu `
          --add-data "tasarim.html;." `
          --add-data "logo.webp;." `
          --add-data "grafik_resmi.png;." `
          --add-data "simulasyon_resmi.png;." `
          --hidden-import xgboost `
          --hidden-import xgboost.sklearn `
          --hidden-import xgboost.core `
          --collect-binaries xgboost `
          --collect-data xgboost `
          --copy-metadata xgboost `
          --hidden-import sklearn.linear_model `
          --hidden-import sklearn.preprocessing `
          --hidden-import sklearn.utils `
          main.py

    - name: Dosyayi Yukle
      uses: actions/upload-artifact@v4
      with:
        name: SatisSimulasyonu-EXE
        path: dist/SatisSimulasyonu/
        compression-level: 0
