name: Windows Exe Olustur

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Kutuphaneleri Yukle
      run: pip install pandas openpyxl pyinstaller scikit-learn xgboost numpy

    - name: EXE Olustur
      run: |
        pyinstaller --noconsole --onedir --name SatisSimulasyonu `
          --add-data "tasarim.html;." `
          --add-data "logo.webp;." `
          --add-data "grafik_resmi.png;." `
          --add-data "simulasyon_resmi.png;." `
          --hidden-import xgboost `
          --hidden-import xgboost.sklearn `
          --collect-all xgboost `
          --hidden-import sklearn `
          --collect-all sklearn `
          main.py

    - name: Dosyayi Yukle
      uses: actions/upload-artifact@v4
      with:
        name: SatisSimulasyonu-EXE
        path: dist/SatisSimulasyonu/
        compression-level: 0
